// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS_BC3ggmPFhsrA7iSKwHE--hzcIYcdy0',
    appId: '1:22826339548:web:354f0b30a8715faf58f819',
    messagingSenderId: '22826339548',
    projectId: 'applet-443b3',
    authDomain: 'applet-443b3.firebaseapp.com',
    storageBucket: 'applet-443b3.appspot.com',
    measurementId: 'G-XDT2B11EX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-wBch10cUCXJmRWulZ4Fnh6lSx2QtRKY',
    appId: '1:22826339548:android:f9be6ff94ccc4bac58f819',
    messagingSenderId: '22826339548',
    projectId: 'applet-443b3',
    storageBucket: 'applet-443b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBasAxqpMdFxvPLDkP6ifwu4UIjtAlaNR0',
    appId: '1:22826339548:ios:6bba615aed0274d658f819',
    messagingSenderId: '22826339548',
    projectId: 'applet-443b3',
    storageBucket: 'applet-443b3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBasAxqpMdFxvPLDkP6ifwu4UIjtAlaNR0',
    appId: '1:22826339548:ios:6bba615aed0274d658f819',
    messagingSenderId: '22826339548',
    projectId: 'applet-443b3',
    storageBucket: 'applet-443b3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS_BC3ggmPFhsrA7iSKwHE--hzcIYcdy0',
    appId: '1:22826339548:web:e3cb6b5e322d829658f819',
    messagingSenderId: '22826339548',
    projectId: 'applet-443b3',
    authDomain: 'applet-443b3.firebaseapp.com',
    storageBucket: 'applet-443b3.appspot.com',
    measurementId: 'G-Q6DS2SHYT8',
  );
}
